ckpt: lightning_logs/version_48/best_checkpoint.ckpt
context_length: 16
dataset: double_well
device: cuda:0
diffusion_config: diffusion_small_config
freq: H
init_skip: False
num_samples: 100
prediction_length: 100
sampler: ddpm
sampler_params:
  guidance: quantile
  scale: 4
setup: forecasting
use_features: False
use_lags: False #true
normalization: true
use_validation_set: False
